### ISSUE TITLE
Can't buy .nl TLD with the script.

### ISSUE THREAD

**Issue by Pa5cal1** [wallopthecat/namecheap-domain-sniper#2]
I can't buy a .nl TLD with the script. I get the following error/message:

[domain].nl is available? true
Addresses: [ { AddressId: 0, AddressName: 'Primary Address', IsDefault: true } ] 

W [Error]: This TLD 'nl' does not support adding or enabling Free whoisguard, domain: [domain].nl
    at za (/home/pi/namecheap-domain-sniper/node_modules/@rqt/namecheap/compile/namecheap.js:334:13)
    at Object.create (/home/pi/namecheap-domain-sniper/node_modules/@rqt/namecheap/compile/namecheap.js:416:20)
    at Object.create (/home/pi/namecheap-domain-sniper/node_modules/@rqt/namecheap/compile/index.js:72:24)
    at search (file:///home/pi/namecheap-domain-sniper/index.mjs:53:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  props: { Number: 2015280 }

**Comment by Pa5cal1** [comment]
Nevermind! I saw that i had to change the following in namecheap.js to make it work:

`;async function za(a, b) {
  const {domain:c, years:d = 1, promo:e, address:g, registrantAddress:f = g, techAddress:l = g, adminAddress:k = g, billingAddress:m = g, nameservers:q = [], whois:u = !0, premium:v = {}} = b;
  b = Y(f, "Registrant");
  const w = Y(l, "Tech"), n = Y(k, "Admin"), p = Y(m, "AuxBilling");
  a = await a("namecheap.domains.create", {DomainName:c, Years:d, PromotionCode:e, ...b, ...w, ...n, ...p, Nameservers:q.join(","), AddFreeWhoisguard: "no", WGEnabled: "no", ...v}, "POST");
  [{b:a}] = V("DomainCreateResult", a);
  return a;
}`
